
server:
  #servlet:
   # context-path: /API
  port: 8081

  feign:
    hystrix:
      enabled: false
    okhttp:
      enabled: true
      
sample:
  client:
    url: http://localhost:8089/api/

management:
  endpoints:
    web:
      exposure:
        include: '*'